package com.sunil.mvp.db.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sunil.mvp.db.model.KickStarter;

import com.sunil.mvp.db.model.KickStarterDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig kickStarterDaoConfig;

    private final KickStarterDao kickStarterDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        kickStarterDaoConfig = daoConfigMap.get(KickStarterDao.class).clone();
        kickStarterDaoConfig.initIdentityScope(type);

        kickStarterDao = new KickStarterDao(kickStarterDaoConfig, this);

        registerDao(KickStarter.class, kickStarterDao);
    }
    
    public void clear() {
        kickStarterDaoConfig.clearIdentityScope();
    }

    public KickStarterDao getKickStarterDao() {
        return kickStarterDao;
    }

}
