package com.sunil.mvp.db.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "KICK_STARTER".
 */
@Entity
public class KickStarter {

    @Id
    private Long id;

    @NotNull
    private String s_no;
    private String amt_pledged;
    private String blurb;
    private String by;
    private String country;
    private String currency;
    private String end_time;
    private String location;
    private String percentage;
    private String num_backers;
    private String state;
    private String title;
    private String type;
    private String url;

    @Generated(hash = 1056162228)
    public KickStarter() {
    }

    public KickStarter(Long id) {
        this.id = id;
    }

    @Generated(hash = 2097938840)
    public KickStarter(Long id, @NotNull String s_no, String amt_pledged, String blurb, String by, String country, String currency, String end_time, String location, String percentage, String num_backers, String state, String title, String type,
            String url) {
        this.id = id;
        this.s_no = s_no;
        this.amt_pledged = amt_pledged;
        this.blurb = blurb;
        this.by = by;
        this.country = country;
        this.currency = currency;
        this.end_time = end_time;
        this.location = location;
        this.percentage = percentage;
        this.num_backers = num_backers;
        this.state = state;
        this.title = title;
        this.type = type;
        this.url = url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getS_no() {
        return s_no;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setS_no(@NotNull String s_no) {
        this.s_no = s_no;
    }

    public String getAmt_pledged() {
        return amt_pledged;
    }

    public void setAmt_pledged(String amt_pledged) {
        this.amt_pledged = amt_pledged;
    }

    public String getBlurb() {
        return blurb;
    }

    public void setBlurb(String blurb) {
        this.blurb = blurb;
    }

    public String getBy() {
        return by;
    }

    public void setBy(String by) {
        this.by = by;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getEnd_time() {
        return end_time;
    }

    public void setEnd_time(String end_time) {
        this.end_time = end_time;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getPercentage() {
        return percentage;
    }

    public void setPercentage(String percentage) {
        this.percentage = percentage;
    }

    public String getNum_backers() {
        return num_backers;
    }

    public void setNum_backers(String num_backers) {
        this.num_backers = num_backers;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
